### ISSUE TITLE
使用国内cdn加速访问

### ISSUE THREAD

**Issue by Lynskylate** [envoyproxy-cn/envoyproxy-cn.io#10]
目前前端资源加载都是从docsy默认的cdn加载，由于国内网络环境，这些cdn部分被墙，或加载速度慢，需要改成国内cdn加速国内访问。

如果顾虑海外访问速度，可以选择有海外加速的cdn

**Comment by zyfjeff** [comment]
主要面向国内，如果启用cdn，那整体的访问速度应该可以大幅度提高?

**Comment by Lynskylate** [comment]
![image](https://user-images.githubusercontent.com/17235904/92349645-5453d000-f109-11ea-90d8-c1bc9fbd4b02.png)
能优化一大半，目前envoyproxy.github.io 单纯这个html测试时根据网络情况能占用500ms-4s时间，js，css资源需要占用5s+时间。jquery由于被墙，导致动画无法加载，部分函数也存在错误

**Comment by Lynskylate** [comment]
当然最好的方案是上传到阿里云oss，或者腾讯云cos，通过cdn分发。
但是如果hugo生成的静态网址中的js，css都是使用海外cdn的话，速度还是会被拖慢。

**Comment by helight** [comment]
我现在把这几个文件都放到站点了，已经独立了域名管理。
http://www.envoyproxy.org.cn/
国内直接访问，速度也不慢，还可以接受，大家也测试一下。
