### ISSUE TITLE
集成博客评论插件

### ISSUE THREAD

**Issue by zyfjeff** [envoyproxy-cn/envoyproxy-cn.io#6]
目前的博客、文档都没有集成评论，是否有必要集成下评论插件到网站上 @Lynskylate 可以调研看看?

**Comment by helight** [comment]
我用的是gtalk，感觉还可以

**Comment by Lynskylate** [comment]
目前社区主流评论系统主要有基于disqus等服务提供商，基于github issue的评论系统两种，disqus等系统服务提供商基本被gfw封杀，因此使用github issue搭建更符合我们中文社区的需求。

調研了下現有基於github issue 實現評論的方案
* gitment  長久不維護，看它quick start的時候，发现其需要將secret id等密钥写入前端的明文代码，虽然其作者声称其安全性无问题，但是考虑其维护程度，我不是很推荐。
* [gitalk](https://github.com/gitalk/gitalk) 同gitment类似，不过维护程度要好不少， 使用preact实现
* [vssue](https://vssue.js.org/zh/guide/getting-started.html) 同gitalk类似，于gitalk的区别可参考其[项目说明](https://vssue.js.org/zh/guide/#与类似项目的比较)，vssue能够支持gitea等非github平台的支持。
* [utterances](https://github.com/utterance/utterances) 使用github app方式进行授权，安全程度相对好很多。

由于我们是使用hugo，vssue，gitalk分别对于vue，react构建工具的支持对我们是无用的，这三个项目使用都较为简单，考虑到安全性，我目前会基于utterances去实现我们的评论系统。

参考资料:
1. [gitment的安全性争议](https://blog.wolfogre.com/posts/security-problem-of-gitment/)
2. [更好的基于 github issues 的评论系统——utterances](https://www.xianmin.org/post/utterances-comment-system/)
